### ISSUE TITLE
Missing dependency rapito:meteor-twit

### ISSUE THREAD

**Issue by jsep** [rapito/manejan-do#3]
I'm trying to get running the project but I can't because this missing dependency `rapito:meteor-twit`.

Please publish the package to atmosphere or add the package as submodule.

**Comment by rapito** [comment]
@jsep that package is already published under another developer name, but it was kind of deprecated so I had to fork it and update it. I believe the project is pointing to my fork isnt it?

**Comment by jsep** [comment]
Yes that's the problem

**Comment by rapito** [comment]
@jsep The submodules were badly set up, I will push the update soon. Thanks!
